import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header className="w-full border-b">
          <nav className="max-w-5xl mx-auto flex items-center justify-between p-4">
            <div className="flex gap-4">
              <Link href="/">Home</Link>
              <Link href="/store">Store</Link>
              <Link href="/games">Games</Link>
              <Link href="/notifications">Notifications</Link>
              <Link href="/profile">Profile</Link>
            </div>
            <div className="flex gap-3">
              <Link href="/api/auth/signin" className="underline">Sign in</Link>
              <Link href="/api/auth/signout" className="underline">Sign out</Link>
            </div>
          </nav>
        </header>
        <main className="max-w-5xl mx-auto p-4">{children}</main>
      </body>
    </html>
  );
}
